language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "pypy"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install jinja2; wget -O- http://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar zx; ln -s shunit2-2.1.6 shunit2
# command to run tests, e.g. python setup.py test
script:  nosetests test_*.py
