#!/usr/bin/python
#---------------------------------------------------------------
# Project         : adminkit
# File            : adminkit
# Copyright       : (C) 2010 Splitted-Desktop Systems
#                   (C) 2010,2012 Frederic Lepied
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Author          : Frederic Lepied
# Created On      : Thu Jan 14 23:12:31 2010
# Purpose         : main script to execute the adminkit rules.
#---------------------------------------------------------------


import os
import sys

try:
    from adminkit import init, finalize
    from plan import Plan
except:
    sys.path = ['/usr/share/adminkit'] + sys.path
    from adminkit import init, finalize
    from plan import Plan

plan = Plan()

CFGFILE = init(plan)

# safety check
if not os.path.isfile(CFGFILE):
    sys.exit(0)

globals = {'define_domain': plan.define_domain,
           'add_var': plan.add_var_host,
           'add_to_list': plan.add_to_list_host,
           'get_var': plan.get_var,
           'add_roles': plan.add_roles,
           }

execfile(CFGFILE, globals)

sys.exit(finalize(plan))

# adminkit ends here
