#!/usr/bin/python
#---------------------------------------------------------------
# Project         : adminkit
# File            : adminkit
# Copyright       : Splitted-Desktop Systems, 2010
# Author          : Frederic Lepied
# Created On      : Thu Jan 14 23:12:31 2010
# Purpose         : main script to execute the adminkit rules.
#---------------------------------------------------------------


import os
import sys

try:
    from adminkit import *
except:
    sys.path = ['/usr/share/adminkit'] + sys.path
    from adminkit import *

init()

CFGDIR = init()
CFGFILE = os.path.join(CFGDIR, 'adminkit.conf')

# safety check
if not os.path.isfile(CFGFILE):
    sys.exit(0)

execfile(CFGFILE)

finalize()

# adminkit ends here
